[firebase]
api_key = "AIzaSyCLlBidr2exd31L4MmvycosQb5etwidx-g"

[cloudinary]
cloud_name = "drkbgxfby"
api_key = "715388784579819"
api_secret = "g4F1IJlAAoCnkP0AMWHLETUZar0"

[gemini]
api_key = "AIzaSyDyE0ihsBrBNgDQZ7jsGfCJS8iJgp5lBtQ"
