[firebase]
api_key = "AIzaSyCLlBidr2exd31L4MmvycosQb5etwidx-g"

[cloudinary]
cloud_name = "drkbgxfby"
api_key = "715388784579819"
api_secret = "g4F1IJlAAoCnkP0AMWHLETUZar0"

[gemini]
api_key = "AIzaSyDyE0ihsBrBNgDQZ7jsGfCJS8iJgp5lBtQ"

[firebase_service_account]
type = "service_account"
project_id = "lvtn2026"
private_key_id = "13fe2183153181aabe6f9e533269eafa2922d07f"

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDJdQrnKZxsqJZt
xFWSiLQAs2BQ3HHXSKP08G86sosDIKFhmmLYBjleXvD0+gm+eKsaoi6Y1o72lm5G
M7zRb0hrclSxEZONbkn/e3wlTRNcBlnZLjwQ5NXu10lgQ0W7+qb2PvKZ19+W3Q+E
v2BLwKxftTO6BWwyfb6jeVH01Qp1MGr2Tz/fIRj7uR3JFZQSWUnu5GKzRjzDd1KX
69+BSg+PYIMag7NohBJrMDWzU1+y4cE748pZr+ozE4fxloE4R8tVG7T5FGuY2J+s
dtVTKRBJ2+6jAPGaAcYCsRX4q/unpkRs39xw4X1wWXwmsrmnc3WkaciWNMlPWabx
Oq5KlRFpAgMBAAECggEABuhlYq/hCh1IRjSG9M63nGAKN7pCtDhMjfCEzIk/fhtA
nrYHuQ2n6oSxzrai/lCJLnE8ojdA4PNKI0xbchOBUv+Gkv6YgISf/duMPNkHxp5S
9vZbGdRc7RMIVDLjqYp9WTYnRQTw042aM6nebuPeYpbrfS+51ME4zUZypoURFhuj
7yjhg8m4zShtXSPoPj8or9oQula8wP3sae0xtUy90o43NipEY/QGjSlxAIKuYeUz
UFmMgtGznKKxiRKIKAcEiyGF93BPqzJqWLm1RpNClkk+wGOMcVg62BsEHS9r0nav
jLZ2fBj3iK6SBhvInjEAh7oJDfu/Np+XxPh+W31EcQKBgQD/6QreLI/DHGP2HbfH
x7s7XrbEYQBhVRfQoXHCI1DwkB3cgLsK+AHWK3+8+xjBD/HbH7J8npfkPngPoMVC
s9C99+G/3yJ5dXvAXwYI1FuuX2PGzysm2MaBC+qfoBD8NolUZHuN697hz6vH60D6
ndsIuggC7068K6xHlZWpyA8eeQKBgQDJhx18omgudLFKELbL3teTGiS7sLEq+3cm
4e9/bavU/x0VgUxihmZ3j3Az149CcYZVbo65QwSR55rPSVCUaRN+ONrXxEn7zSUY
K4noihOBRFGF8VDDXfIRr5ZDg+erVwZQTR8hbKklv0Nv0Bj0Jn5TtDERbgTF2HNz
u5dsgq4OcQKBgG8UmdoMX66iQSWQirhWEwhXOWAOdtrI09iEa1uIdtakx8Fxwz6k
ni93nC/Mklci86lYneIH+QhisTyfXWBxqtb6pOvjEBTGkRvUY0sr2kvbLfUa8bEg
ATH8mTAGi7jed0fBgfv9eTZtLTRPAlqGcI/eKCIV/AgjsNk1rcwPgbiJAoGBALEp
S52+dBGq2hQ/X0MX8rFJwVMSgJ1FlTikVFPUiMNlRh8anJjciAXBHiUk8ba6cBp4
Z5Wrub++OBTT4bemK9HBj3kxAM0QSfTWiZTYlU8FTRmPy60D0IMFtfZCZg31IgLD
2YMbsBMT8efAq78ue81/0cb9zcpTfyMVnYdx1iuxAoGBAJhfsYc1K58DDIUYbtWp
XVf79y4keQGPm+wZs1kasQaOgdX/Xpg1s/cubLYjpzuJrHz3QdR/pkZOo+ZTYCb6
hvTGt1ZpnMaon2f6hPvVLVVx4Oi4QenLxA1OkED+DY9Nv3Yi7+vk+gsIUmrU8xbU
4gMRuyRSrs6sXlDGg3Ms9zeB
-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-fbsvc@lvtn2026.iam.gserviceaccount.com"
client_id = "114162784404752893638"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40lvtn2026.iam.gserviceaccount.com"
universe_domain = "googleapis.com"